{{- if eq .Values.testing.framework "guidellm" }}
apiVersion: v1
kind: Pod
metadata:
  name: benchmark-{{- .Values.inference.serviceName}}
spec:
  containers:
    - name: worker
      command: [ "/bin/sh", "-c", "guidellm benchmark run && sleep infinity" ] # Sleep infinity to allow retrieving report
      image: ghcr.io/vllm-project/guidellm@sha256:24c9e85f807cb6936ee401e6abdb311236c55cd62ec10fc306307e9384c15f9f
      env:
        - name: GUIDELLM_TARGET
          value: "http://{{- .Values.inference.serviceName -}}.{{- .Values.inference.serviceNamespace -}}:{{- .Values.service.port -}}"
        - name: GUIDELLM_RATE_TYPE
          value: "{{- .Values.testing.parameters.rateType  -}}"
        - name: GUIDELLM_MAX_SECONDS
          value: "{{- .Values.testing.parameters.maxSeconds }}"
        - name: GUIDELLM_DATA
          value: "{{- .Values.testing.parameters.data }}"
        - name: GUIDELLM__OPENAI__MAX_OUTPUT_TOKENS
          value: "{{- .Values.testing.parameters.maxOutputTokens}}"
{{- end }}
