apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mpi-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeflow/mpi-operator.git
    targetRevision: v0.4.0
    path: deploy/v2beta1
  destination:
    server: https://kubernetes.default.svc
    namespace: mpi-operator
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
