model: CompVis/ldm-text2im-large-256

modelParameters:
  pipeline: diffusion

inference:
  serviceName: latent-diffusion-diffusers
  serviceNamespace: default
  accelerator: gpu
  framework: diffusers

  modelServer:
    image:
      repository: diffusers/diffusers-pytorch-cuda
      tag: latest
    deployment:
      instanceType: g6e.2xlarge
