model: meta-llama/Llama-3.1-8B-Instruct

modelParameters:
  gpuMemoryUtilization: 0.8
  maxModelLen: 1024
  maxNumSeqs: 1
  maxNumBatchedTokens: 1024
  tokenizerPoolSize: 4
  maxParallelLoadingWorkers: 2
  pipelineParallelSize: 1
  tensorParallelSize: 2
  enablePrefixCaching: false
  numGpus: 1

inference:
  serviceName: llama-31-8b-ray-vllm-nrn
  serviceNamespace: default
  accelerator: neuron
  framework: ray-vllm

  modelServer:
    image:
      repository: 975050295866.dkr.ecr.us-west-2.amazonaws.com/ray-vllm-neuron
      tag: 2.47.0-0.9.1
    deployment:
      instanceType: trn1.2xlarge
