model: NousResearch/Llama-3.2-1B

modelParameters:
  gpuMemoryUtilization: 0.8
  maxModelLen: 8192
  pipelineParallelSize: 1
  tensorParallelSize: 1

inference:
  serviceName: llama-32-1b-aibrix
  serviceNamespace: default
  accelerator: gpu
  framework: aibrix

  modelServer:
    image:
      repository: vllm/vllm-openai
      tag: v0.9.1
