model: Shitao/OmniGen-v1

modelParameters:
  pipeline: omnigen

inference:
  serviceName: omni-gen-diffusers
  serviceNamespace: default
  accelerator: gpu
  framework: diffusers

  modelServer:
    image:
      repository: diffusers/diffusers-pytorch-cuda
      tag: latest
    deployment:
      instanceType: g6e.2xlarge
