model: meta-llama/Llama-3.1-8B-Instruct

modelParameters:
  gpuMemoryUtilization: 0.8
  maxModelLen: 1024
  tensorParallelSize: 2

inference:
  serviceName: llama-31-8b-vllm-nrn
  serviceNamespace: default
  accelerator: neuron
  framework: vllm

  modelServer:
    image:
      repository: public.ecr.aws/q9t5s3a7/vllm-neuron-release-repo
      tag: v0.9.1
    deployment:
      resources:
        neuron:
          requests:
            memory: 50Gi
