apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: gitlab
    repoURL: https://charts.gitlab.io/
    targetRevision: "9.1.1"
    helm:
      values: |
        installCertmanager: false
        global:
          edition: ce
          hosts:
            domain: ${domain}
          ingress:
            configureCertmanager: false
          tls:
            enabled: false
        ingress:
          enabled: false
          configureCertmanager: false
          tls:
            enabled: false
        certmanager-issuer:
          email: $EMAIL
        nginx-ingress:
          controller:
            enabled: false
            service:
              targetPorts:
                https: http
              annotations:
                service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
                service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
                service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
                service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
                service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
                service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: 3600
                service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${acm_certificate_arn}"
                service.beta.kubernetes.io/load-balancer-source-ranges: "0.0.0.0/0"
            config:
              use-http2: "true"
              proxy-real-ip-cidr: ${proxy-real-ip-cidr}
              use-proxy-protocol: "true"
        upgradeCheck:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
