apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gitlab
    helm:
      values: |
        installCertmanager: false
        gitlab:
          ingress:
            className: nginx
            tls:
              enabled: false
          kas:
            ingress:
              enabled: false
        global:
          edition: ce
          hosts:
            domain: ${domain}
          ingress:
            configureCertmanager: false
            class: nginx
            tls:
              enabled: false
        ingress:
          enabled: false
          class:
            name: nginx
          configureCertmanager: false
          tls:
            enabled: false
        certmanager-issuer:
          email: $EMAIL
        minio:
          ingress:
            enabled: false
        nginx-ingress:
          enabled: false
        upgradeCheck:
          enabled: false
    repoURL: https://charts.gitlab.io/
    targetRevision: 9.1.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
